(()=>{
const root=document.getElementById('celestial-coordinate-root');if(!root)return;
const DATA={Sun:{type:'SUN',ra:0,dec:0,description:'The Sun follows the ecliptic and reaches declinations of about ±23.44°.'},Polaris:{type:'STAR',ra:2.5303,dec:89.2641,description:'Polaris lies close to the North Celestial Pole and is an excellent demonstration of latitude and circumpolar motion.'},Sirius:{type:'STAR',ra:6.7525,dec:-16.7161,description:'Sirius is the brightest star in the night sky and lies in Canis Major.'},Betelgeuse:{type:'STAR',ra:5.9195,dec:7.4071,description:'Betelgeuse is a red supergiant in Orion.'},Vega:{type:'STAR',ra:18.6156,dec:38.7837,description:'Vega is a bright A type star in Lyra and a vertex of the Summer Triangle.'},Mars:{type:'PLANET',ra:5,dec:22,description:'Mars is shown with a representative educational RA/Dec position.'},Jupiter:{type:'PLANET',ra:3,dec:16,description:'Jupiter is shown with a representative educational RA/Dec position.'},Saturn:{type:'PLANET',ra:21,dec:-18,description:'Saturn is shown with a representative educational RA/Dec position.'},Moon:{type:'MOON',ra:8,dec:20,description:'The Moon is shown with a representative educational RA/Dec position.'},Andromeda:{type:'GALAXY',ra:.712,dec:41.27,description:'M31, the Andromeda Galaxy, is a deep sky object located using RA and Dec.'},'Orion Nebula':{type:'NEBULA',ra:5.588,dec:-5.39,description:'M42, the Orion Nebula, is a bright stellar nursery in Orion.'},'Sagittarius A*':{type:'BLACK HOLE',ra:17.761,dec:-29.0078,description:'Sagittarius A* is the compact radio source associated with the Milky Way Galactic Center.'}};
const ALIASES={'north star':'Polaris','sgr a*':'Sagittarius A*','m31':'Andromeda','m42':'Orion Nebula'};
root.innerHTML=`<div class="cc3d-app"><header class="cc3d-header"><div><div class="cc3d-kicker">SCIEX / ASTRONOMY</div><h1>Celestial Coordinate Simulator</h1><p>Build and explore the observer-centered celestial sphere.</p></div><div class="cc3d-status" id="status">STEP 1 / 7</div></header><div class="cc3d-search"><input id="target" list="objects" placeholder="Enter a star, planet, Moon, galaxy, nebula..."/><datalist id="objects"></datalist><button id="generate">Generate</button></div><div class="cc3d-layout"><section class="cc3d-stage" id="stage"><canvas id="canvas"></canvas><div class="cc3d-overlay"><b id="stepTitle">Reference Sphere</b><span id="stepText">Earth and the observer are at the exact center of the celestial sphere.</span></div><div class="cc3d-readout" id="readout"></div><div class="cc3d-controls"><button id="prev">‹ Previous</button><button id="play">Build ▶</button><button id="next">Next ›</button><button id="reset">Reset</button><button id="view">Observer View</button></div></section><aside class="cc3d-panel"><section><h3>OBSERVER</h3><label>Latitude <b id="latValue">26.85° N</b></label><input id="lat" type="range" min="-90" max="90" step="0.1" value="26.85"/><label>Longitude <b id="lonValue">80.95° E</b></label><input id="lon" type="range" min="-180" max="180" step="0.1" value="80.95"/></section><section><h3>TIME</h3><div class="cc3d-live"><button id="live">● LIVE TIME</button><span id="clock">--:--:-- UTC</span></div><input id="date" type="datetime-local"/><button id="now">Use Current Time</button></section><section><h3>BUILD SEQUENCE</h3><div class="cc3d-steps" id="steps"></div></section><section><h3>REFERENCE GRIDS</h3><label><input id="sphereGrid" type="checkbox" checked/> Celestial Sphere Grid</label><label><input id="horizon" type="checkbox" checked/> Horizon & cardinal points</label><label><input id="equator" type="checkbox" checked/> Equator, RA & poles</label><label><input id="ecliptic" type="checkbox" checked/> Ecliptic & seasonal points</label><label><input id="targetLayer" type="checkbox" checked/> Target & coordinate arcs</label><label><input id="labels" type="checkbox" checked/> Large Labels</label></section><section class="cc3d-note" id="note"></section></aside></div></div>`;
Object.keys(DATA).forEach(k=>{const o=document.createElement('option');o.value=k;document.getElementById('objects').appendChild(o)});
const s=document.createElement('script');s.src='https://cdnjs.cloudflare.com/ajax/libs/three.js/r128/three.min.js';s.onload=()=>{try{build()}catch(e){console.error(e);root.innerHTML='<div class="cc-error">3D simulator failed.<br><small>'+e.message+'</small></div>'}};s.onerror=()=>root.innerHTML='<div class="cc-error">Three.js could not be loaded.</div>';document.head.appendChild(s);
function build(){
const T=window.THREE,canvas=document.getElementById('canvas'),stage=document.getElementById('stage');const scene=new T.Scene();scene.background=new T.Color(0x02050b);const camera=new T.PerspectiveCamera(45,1,.1,60);camera.position.set(8,5.8,8);const renderer=new T.WebGLRenderer({canvas,antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio||1,2));renderer.setClearColor(0x02050b,1);
const R=4.25,earthR=.30;let lat=26.85,lon=80.95,date=new Date(),liveTime=true,step=1,building=false,observer=false,theta=.72,phi=1.02,dist=9,drag=false,lastX=0,lastY=0,targetName='Sun';const root3=new T.Group();scene.add(root3);scene.add(new T.AmbientLight(0xa7bed3,.6));
const labels=new T.Group();root3.add(labels);const layers={sphere:new T.Group(),sphereGrid:new T.Group(),horizon:new T.Group(),equator:new T.Group(),ecliptic:new T.Group(),target:new T.Group()};Object.values(layers).forEach(x=>root3.add(x));
const steps=[['Reference Sphere','Place Earth and the observer at the exact center of the transparent celestial sphere.'],['Celestial Equator & Poles','Extend Earth’s rotation axis to the North and South Celestial Poles and project Earth’s equator outward.'],['Ecliptic','Draw the Sun’s apparent annual path, inclined by 23.44° to the celestial equator.'],['Equinoxes & Solstices','Mark the Vernal and Autumnal Equinoxes and the Summer and Winter Solstices.'],['Target RA & Dec','Locate the selected object using Right Ascension and Declination.'],['Horizon & Meridian','Add the local horizon, cardinal points, zenith, nadir and meridian for this observer.'],['Altitude & Azimuth','Connect the observer to the target and show its altitude, azimuth and hour angle.']];
function mat(c,o=1){return new T.LineBasicMaterial({color:c,transparent:o<1,opacity:o})}function line(points,c=0x7590a8,o=.45,parent=root3){const l=new T.Line(new T.BufferGeometry().setFromPoints(points),mat(c,o));parent.add(l);return l}function label(text,pos,c=0xc9d7e5,size=.48){const cv=document.createElement('canvas'),ctx=cv.getContext('2d');cv.width=1024;cv.height=180;ctx.clearRect(0,0,cv.width,cv.height);ctx.font='700 54px Arial';ctx.fillStyle='#'+c.toString(16).padStart(6,'0');ctx.shadowColor='#000';ctx.shadowBlur=8;ctx.fillText(text,18,72);const tx=new T.CanvasTexture(cv);tx.minFilter=T.LinearFilter;const sp=new T.Sprite(new T.SpriteMaterial({map:tx,transparent:true,depthTest:false}));sp.position.copy(pos);sp.scale.set(size*4.2,size,1);sp.userData.isLabel=true;labels.add(sp);return sp}
function sp(ra,dec,r=R){const a=ra*Math.PI/12,d=dec*Math.PI/180;return new T.Vector3(r*Math.cos(d)*Math.cos(a),r*Math.sin(d),r*Math.cos(d)*Math.sin(a))}function lp(alt,az,r=R){const h=alt*Math.PI/180,a=az*Math.PI/180;return new T.Vector3(r*Math.cos(h)*Math.sin(a),r*Math.sin(h),r*Math.cos(h)*Math.cos(a))}function circle(pts,c,o,p){return line(pts,c,o,p)}
const sphere=new T.Mesh(new T.SphereGeometry(R,64,40),new T.MeshBasicMaterial({color:0x4d6d88,transparent:true,opacity:.055,side:T.BackSide}));layers.sphere.add(sphere);
for(let dec=-75;dec<=75;dec+=15){const pts=[];for(let i=0;i<=256;i++)pts.push(sp(i/256*24,dec,R+.01));circle(pts,0x5b7993,.24,layers.sphereGrid)}
for(let ra=0;ra<24;ra+=1){const pts=[];for(let i=0;i<=256;i++)pts.push(sp(ra,-90+i/256*180,R+.01));circle(pts,0x5b7993,.24,layers.sphereGrid)}
for(let dec=-90;dec<=90;dec+=30)label((dec>0?'+':'')+dec+'° DEC',new T.Vector3(R+.05,dec/90*R,0),0x7994aa,.25);for(let ra=0;ra<24;ra+=2){const p=sp(ra,0,R+.08);label(String(ra).padStart(2,'0')+'h',p,0x7897b1,.24)}
const horizonPts=[];for(let i=0;i<=256;i++)horizonPts.push(lp(0,i/256*360));circle(horizonPts,0xd39262,.9,layers.horizon);for(let az=0;az<360;az+=15)circle([new T.Vector3(0,0,0),lp(0,az,R)],0x5f7182,.14,layers.horizon);[['N',0],['E',90],['S',180],['W',270]].forEach(([n,a])=>label(n,lp(0,a,R+.3),0x8de09a,.48));label('ZENITH',new T.Vector3(0,R+.45,0),0x8de09a,.44);label('NADIR',new T.Vector3(0,-R-.45,0),0x8de09a,.44);label('HORIZON',new T.Vector3(R*.7,0,R*.72),0xe0a47a,.38);
const eqPts=[];for(let i=0;i<=256;i++)eqPts.push(sp(i/256*24,0));circle(eqPts,0x72b0dc,.85,layers.equator);for(let ra=0;ra<24;ra+=2)circle([new T.Vector3(0,0,0),sp(ra,0,R)],0x58758b,.15,layers.equator);label('CELESTIAL EQUATOR',new T.Vector3(R+.1,.2,0),0x9ccff0,.40);const ncp=new T.Vector3(0,R,0),scp=new T.Vector3(0,-R,0);circle([scp.clone().multiplyScalar(1.1),ncp.clone().multiplyScalar(1.1)],0xd1e0eb,.65,layers.equator);label('NCP',new T.Vector3(.2,R+.55,0),0xe0edf6,.44);label('SCP',new T.Vector3(.2,-R-.55,0),0xe0edf6,.44);
const ob=23.44*Math.PI/180,epts=[];for(let i=0;i<=256;i++){const a=i/256*Math.PI*2;epts.push(new T.Vector3(R*Math.cos(a),R*Math.sin(a)*Math.sin(ob),R*Math.sin(a)*Math.cos(ob)))}circle(epts,0xe0a84f,.9,layers.ecliptic);label('ECLIPTIC',new T.Vector3(R+.2,.95,0),0xf0c477,.42);const seasonal=[['VERNAL EQUINOX',sp(0,0,R+.09)],['AUTUMNAL EQUINOX',sp(12,0,R+.09)],['SUMMER SOLSTICE',sp(6,23.44,R+.09)],['WINTER SOLSTICE',sp(18,-23.44,R+.09)]];seasonal.forEach(([n,p])=>{const m=new T.Mesh(new T.SphereGeometry(.085,12,12),new T.MeshBasicMaterial({color:0xffc75c}));m.position.copy(p);layers.ecliptic.add(m);label(n,p.clone().multiplyScalar(1.1),0xffcf73,.30)});
const earth=new T.Mesh(new T.SphereGeometry(earthR,24,16),new T.MeshPhongMaterial({color:0x2e75a4,emissive:0x07151e}));root3.add(earth);const axis=new T.Mesh(new T.CylinderGeometry(.018,.018,R*1.28,10),new T.MeshBasicMaterial({color:0xd6e3ec}));root3.add(axis);label('OBSERVER / EARTH',new T.Vector3(.45,.4,.45),0xe2edf5,.34);
let meridianLine=null,targetMarker=null,targetLine=null,altArc=null,raArc=null,decArc=null,targetLabel=null;
function jd(d){return d.getTime()/86400000+2440587.5}function lst(){const D=jd(date)-2451545;let g=18.697374558+24.06570982441908*D;g=((g%24)+24)%24;return (g+lon/15+24)%24}function altAz(ra,dec){const H=(lst()-ra)*15*Math.PI/180,p=lat*Math.PI/180,d=dec*Math.PI/180;const alt=Math.asin(Math.sin(p)*Math.sin(d)+Math.cos(p)*Math.cos(d)*Math.cos(H));const az=Math.atan2(-Math.sin(H),Math.tan(d)*Math.cos(p)-Math.sin(p)*Math.cos(H));return{alt:alt*180/Math.PI,az:(az*180/Math.PI+360)%360,H:(lst()-ra+24)%24}}
function updateMeridian(){if(meridianLine){layers.horizon.remove(meridianLine);meridianLine.geometry.dispose()}const pts=[];const ra0=lst();for(let i=0;i<=160;i++)pts.push(sp(ra0,-90+i/160*180,R+.025));meridianLine=line(pts,0xd29a70,.75,layers.horizon);label('LOCAL MERIDIAN',new T.Vector3(R*.78,R*.56,.15),0xe1aa7e,.36)}
function clearTarget(){[targetMarker,targetLine,altArc,raArc,decArc,targetLabel].forEach(o=>{if(o){layers.target.remove(o);if(o.geometry)o.geometry.dispose()}});targetMarker=targetLine=altArc=raArc=decArc=targetLabel=null}
function makeTarget(){clearTarget();const q=document.getElementById('target').value.trim();const key=ALIASES[q.toLowerCase()]||Object.keys(DATA).find(k=>k.toLowerCase()===q.toLowerCase())||Object.keys(DATA).find(k=>k.toLowerCase().includes(q.toLowerCase()));if(!key)return;targetName=key;const o=DATA[key],p=sp(o.ra,o.dec,R+.03);targetMarker=new T.Mesh(new T.SphereGeometry(.13,16,16),new T.MeshBasicMaterial({color:0xffd267}));targetMarker.position.copy(p);layers.target.add(targetMarker);targetLine=line([new T.Vector3(0,0,0),p],0xffc65c,1,layers.target);const a=altAz(o.ra,o.dec),ground=lp(0,a.az,R);const altPts=[];for(let i=0;i<=64;i++){const t=i/64;altPts.push(ground.clone().lerp(new T.Vector3(0,0,0),t))}altArc=line(altPts,0xff9a62,.9,layers.target);const raPts=[];for(let i=0;i<=80;i++)raPts.push(sp(i/80*o.ra,o.dec,R+.045));raArc=line(raPts,0x7ec8ff,.75,layers.target);const decPts=[];for(let i=0;i<=80;i++)decPts.push(sp(o.ra,-90+(i/80)*(o.dec+90),R+.05));decArc=line(decPts,0xc49cff,.75,layers.target);targetLabel=label(key,p.clone().multiplyScalar(1.13),0xffd875,.46);updateReadout(key,o,a)}
function updateReadout(k,o,a){document.getElementById('readout').innerHTML='<b>'+k+'</b><span>'+o.type+'</span><span>RA '+o.ra.toFixed(4)+' h</span><span>Dec '+(o.dec>=0?'+':'')+o.dec.toFixed(3)+'°</span><span>Hour Angle '+a.H.toFixed(3)+' h</span><span>Altitude '+a.alt.toFixed(2)+'°</span><span>Azimuth '+a.az.toFixed(2)+'°</span><span>LST '+lst().toFixed(3)+' h</span>';document.getElementById('note').textContent=o.description+' Observer: '+Math.abs(lat).toFixed(1)+'° '+(lat>=0?'N':'S')+', '+Math.abs(lon).toFixed(1)+'° '+(lon>=0?'E':'W')+'.'}
function setStep(n){step=Math.max(1,Math.min(7,n));document.getElementById('status').textContent='STEP '+step+' / 7';document.getElementById('stepTitle').textContent=steps[step-1][0];document.getElementById('stepText').textContent=steps[step-1][1];document.querySelectorAll('#steps button').forEach((b,i)=>b.classList.toggle('active',i<step));layers.sphere.visible=true;layers.sphereGrid.visible=document.getElementById('sphereGrid').checked&&step>=1;layers.equator.visible=document.getElementById('equator').checked&&step>=2;layers.ecliptic.visible=document.getElementById('ecliptic').checked&&step>=3;layers.horizon.visible=document.getElementById('horizon').checked&&step>=6;layers.target.visible=document.getElementById('targetLayer').checked&&step>=5;labels.visible=document.getElementById('labels').checked;earth.visible=step>=1;axis.visible=step>=2;document.getElementById('play').textContent=building?'Pause ⏸':'Build ▶'}
const stepsEl=document.getElementById('steps');steps.forEach((x,i)=>{const b=document.createElement('button');b.textContent=(i+1)+'. '+x[0];b.onclick=()=>setStep(i+1);stepsEl.appendChild(b)});
function rebuild(){makeTarget();updateMeridian();setStep(step)}function clockText(){const u=date;return u.toISOString().slice(0,19).replace('T',' ')+' UTC'}
function cameraUpdate(){if(observer){camera.position.set(.001,.001,.001);camera.lookAt(new T.Vector3(0,0,-R));return}const d=new T.Vector3(Math.sin(theta)*Math.sin(phi)*dist,Math.cos(phi)*dist,Math.cos(theta)*Math.sin(phi)*dist);camera.position.lerp(d,.12);camera.lookAt(0,0,0)}
function resize(){const w=Math.max(1,stage.clientWidth),h=Math.max(1,stage.clientHeight);renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix()}
document.getElementById('generate').onclick=()=>rebuild();document.getElementById('target').onkeydown=e=>{if(e.key==='Enter')rebuild()};document.getElementById('prev').onclick=()=>setStep(step-1);document.getElementById('next').onclick=()=>setStep(step+1);document.getElementById('play').onclick=()=>{building=!building};document.getElementById('reset').onclick=()=>{building=false;step=1;observer=false;theta=.72;phi=1.02;dist=9;setStep(1)};document.getElementById('view').onclick=()=>{observer=!observer;document.getElementById('view').textContent=observer?'Universe View':'Observer View'};
document.getElementById('lat').oninput=e=>{lat=+e.target.value;document.getElementById('latValue').textContent=Math.abs(lat).toFixed(1)+'° '+(lat>=0?'N':'S');rebuild()};document.getElementById('lon').oninput=e=>{lon=+e.target.value;document.getElementById('lonValue').textContent=Math.abs(lon).toFixed(1)+'° '+(lon>=0?'E':'W');rebuild()};
document.getElementById('live').onclick=()=>{liveTime=!liveTime;document.getElementById('live').classList.toggle('active',liveTime);if(liveTime){date=new Date();document.getElementById('date').value=date.toISOString().slice(0,16);rebuild()}};document.getElementById('now').onclick=()=>{liveTime=true;document.getElementById('live').classList.add('active');date=new Date();document.getElementById('date').value=date.toISOString().slice(0,16);rebuild()};document.getElementById('date').value=date.toISOString().slice(0,16);document.getElementById('date').onchange=e=>{liveTime=false;document.getElementById('live').classList.remove('active');date=new Date(e.target.value);rebuild()};
['labels','sphereGrid','targetLayer','equator','ecliptic','horizon'].forEach(id=>document.getElementById(id).onchange=()=>setStep(step));canvas.addEventListener('pointerdown',e=>{if(observer)return;drag=true;lastX=e.clientX;lastY=e.clientY;canvas.setPointerCapture(e.pointerId)});canvas.addEventListener('pointermove',e=>{if(!drag)return;theta-=(e.clientX-lastX)*.006;phi=Math.max(.12,Math.min(3.02,phi+(e.clientY-lastY)*.006));lastX=e.clientX;lastY=e.clientY});canvas.addEventListener('pointerup',()=>drag=false);canvas.addEventListener('wheel',e=>{e.preventDefault();dist=Math.max(5,Math.min(18,dist*Math.exp(e.deltaY*.001)))});window.addEventListener('resize',resize);
let last=performance.now(),buildAccumulator=0;function animate(now){const dt=Math.min(.05,(now-last)/1000);last=now;if(liveTime)date=new Date();if(building){buildAccumulator+=dt;if(buildAccumulator>.9){buildAccumulator=0;if(step<7)setStep(step+1);else building=false}}updateMeridian();if(targetName){const o=DATA[targetName];if(o){const a=altAz(o.ra,o.dec);updateReadout(targetName,o,a)}}document.getElementById('clock').textContent=clockText();cameraUpdate();renderer.render(scene,camera);requestAnimationFrame(animate)}
document.getElementById('target').value='Sun';document.getElementById('live').classList.add('active');rebuild();resize();requestAnimationFrame(animate);
}
})();