(()=>{
const root=document.getElementById('emlab-root');
if(!root)return;
root.innerHTML=`<div class="emlab"><header class="emtop"><div><small>SCIEX · PHYSICS LABORATORY</small><h1>Electric & Electromagnetic Field Laboratory</h1><small>SI calibrated computational physics · 2D laboratory plane</small></div><strong>● SI</strong></header><main class="emmain"><section class="stage"><canvas id="em-canvas"></canvas><div class="hud" id="em-hud"></div><div class="hint">Click to add/select charges · drag charges · scroll to zoom</div></section><aside class="panel"><div class="tabs"><button class="active" data-mode="coulomb">Coulomb</button><button data-mode="field">E Field</button><button data-mode="potential">Potential</button><button data-mode="gauss">Gauss</button><button data-mode="ampere">Ampère</button><button data-mode="lorentz">Lorentz</button></div><section><h3>Sources</h3><div class="row"><button id="em-plus">+ Charge</button><button id="em-minus">− Charge</button><button id="em-wire">Current Wire</button><button id="em-reset">Reset</button></div><label>Charge <output id="em-qout">+1.00 nC</output><input id="em-q" type="range" min="-10" max="10" step="0.1" value="1"></label><label>Current <output id="em-iout">10 A</output><input id="em-cur" type="range" min="-50" max="50" value="10"></label></section><section><h3>Visualization</h3><label><input id="em-lines" type="checkbox" checked> Field lines</label><label><input id="em-vectors" type="checkbox" checked> Field vectors</label><label><input id="em-equip" type="checkbox"> Equipotential lines</label></section><section><h3>Gaussian / Amperian Probe</h3><label>Radius <output id="em-rout">1.50 m</output><input id="em-rad" type="range" min="0.3" max="3" step="0.05" value="1.5"></label></section><section><h3>Test Particle</h3><div class="row"><button id="em-electron">Electron</button><button id="em-proton">Proton</button></div><div class="grid2"><label>x (m)<input id="em-px" value="0" type="number" step="0.1"></label><label>y (m)<input id="em-py" value="1.2" type="number" step="0.1"></label><label>vx (m/s)<input id="em-vx" value="1000000" type="number"></label><label>vy (m/s)<input id="em-vy" value="0" type="number"></label></div><div class="row"><button id="em-place">Place</button><button id="em-run">Run</button><button id="em-pause">Pause</button><button id="em-clear">Clear path</button></div></section><section><h3>Measured quantities</h3><pre class="read" id="em-read"></pre><div class="formula" id="em-formula"></div></section></aside></main></div>`;
const cv=document.getElementById('em-canvas'),ctx=cv.getContext('2d');
const $=id=>document.getElementById(id);
const K=8.9875517923e9,EPS=8.8541878128e-12,MU=1.25663706212e-6,ECH=1.602176634e-19,ME=9.1093837139e-31,MP=1.67262192369e-27;
let mode='coulomb',charges=[],wires=[],particle=null,running=false,qParticle=-ECH,mParticle=ME,path=[],zoom=65,ox=0,oy=0,drag=null,last={x:0,y:0};
function size(){const r=cv.getBoundingClientRect(),d=Math.min(window.devicePixelRatio||1,2);cv.width=Math.max(1,r.width*d);cv.height=Math.max(1,r.height*d);ctx.setTransform(d,0,0,d,0,0);draw()}
function world(){return{w:cv.clientWidth||800,h:cv.clientHeight||600}}
function W(x,y){const s=world();return{x:s.w/2+ox+x*zoom,y:s.h/2+oy-y*zoom}}
function P(x,y){const s=world();return{x:(x-s.w/2-ox)/zoom,y:-(y-s.h/2-oy)/zoom}}
function charge(q,x,y){return{id:Math.random(),q,x,y}}
function reset(){charges=[charge(1e-9,-1.15,0),charge(-1e-9,1.15,0)];wires=[];particle=null;path=[];running=false;draw()}
function E(x,y){let ex=0,ey=0;for(const a of charges){const dx=x-a.x,dy=y-a.y,r2=Math.max(dx*dx+dy*dy,.0025),f=K*a.q/Math.pow(r2,1.5);ex+=f*dx;ey+=f*dy}return{ex,ey}}
function V(x,y){let v=0;for(const a of charges)v+=K*a.q/Math.max(Math.hypot(x-a.x,y-a.y),.05);return v}
function B(x,y){let bz=0;for(const w of wires){const r=Math.max(Math.hypot(x-w.x,y-w.y),.05);bz+=MU*w.I/(2*Math.PI*r)}return bz}
function force(){if(!particle)return null;const e=E(particle.x,particle.y),b=B(particle.x,particle.y);const fx=qParticle*(e.ex-particle.vy*b),fy=qParticle*(e.ey+particle.vx*b);return{ex:e.ex,ey:e.ey,b,fx,fy,f:Math.hypot(fx,fy)}}
function grid(){const s=world();ctx.strokeStyle='#122636';ctx.lineWidth=1;for(let x=-8;x<=8;x++)for(let y=-5;y<=5;y++){let a=W(x,y),b=W(x+1,y);ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke()}for(let x=-8;x<=8;x++){let a=W(x,-5),b=W(x,5);ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke()}}
function sources(){for(const a of charges){const p=W(a.x,a.y);ctx.beginPath();ctx.arc(p.x,p.y,13,0,Math.PI*2);ctx.fillStyle=a.q>=0?'#4285ff':'#ed4b5b';ctx.shadowBlur=14;ctx.shadowColor=ctx.fillStyle;ctx.fill();ctx.shadowBlur=0;ctx.fillStyle='#fff';ctx.font='bold 12px system-ui';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(a.q>=0?'+':'−',p.x,p.y)}for(const w of wires){const p=W(w.x,w.y);ctx.fillStyle='#c9d2d9';ctx.fillRect(p.x-5,p.y-5,10,10)}}
function vectors(){for(let x=-7.5;x<=7.5;x+=.7)for(let y=-4.5;y<=4.5;y+=.7){const e=E(x,y),m=Math.hypot(e.ex,e.ey);if(m<1e-8)continue;const p=W(x,y),ux=e.ex/m,uy=-e.ey/m,l=10;ctx.strokeStyle='#5c91c4';ctx.beginPath();ctx.moveTo(p.x-ux*l,p.y-uy*l);ctx.lineTo(p.x+ux*l,p.y+uy*l);ctx.stroke()}}
function fieldLines(){for(const a of charges){for(let i=0;i<16;i++){const ang=2*Math.PI*i/16;let x=a.x+.14*Math.cos(ang),y=a.y+.14*Math.sin(ang);ctx.strokeStyle=a.q>=0?'rgba(66,133,255,.55)':'rgba(237,75,91,.55)';ctx.beginPath();for(let n=0;n<180;n++){const p=W(x,y);n?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y);const e=E(x,y),m=Math.hypot(e.ex,e.ey);if(m<1e-8)break;const sign=a.q>=0?1:-1;x+=sign*e.ex/m*.045;y+=sign*e.ey/m*.045;if(Math.abs(x)>8||Math.abs(y)>5)break}ctx.stroke()}}}
function probe(){const r=+$('em-rad').value,p=W(0,0);ctx.strokeStyle='#ffd45a';ctx.lineWidth=2;ctx.beginPath();ctx.arc(p.x,p.y,r*zoom,0,2*Math.PI);ctx.stroke();let enclosed=0;for(const a of charges)if(a.x*a.x+a.y*a.y<=r*r)enclosed+=a.q;return enclosed}
function particleDraw(){if(!particle)return;const p=W(particle.x,particle.y);if(path.length>1){ctx.strokeStyle='rgba(255,212,90,.7)';ctx.beginPath();path.forEach((v,i)=>{const z=W(v.x,v.y);i?ctx.lineTo(z.x,z.y):ctx.moveTo(z.x,z.y)});ctx.stroke()}ctx.fillStyle='#ffd45a';ctx.beginPath();ctx.arc(p.x,p.y,7,0,2*Math.PI);ctx.fill()}
function readout(){const r=$('em-read'),f=$('em-formula');if(mode==='coulomb'){const a=charges[0],b=charges[1]||a,d=Math.max(Math.hypot(a.x-b.x,a.y-b.y),.001),F=K*Math.abs(a.q*b.q)/(d*d);r.textContent=`separation = ${d.toFixed(4)} m\nforce = ${F.toExponential(4)} N\ninteraction = ${a.q*b.q<0?'attractive':'repulsive'}`;f.textContent='F = k |q₁q₂| / r²'}else if(mode==='field'){const e=E(last.x,last.y);r.textContent=`probe = (${last.x.toFixed(2)}, ${last.y.toFixed(2)}) m\nEx = ${e.ex.toExponential(4)} N/C\nEy = ${e.ey.toExponential(4)} N/C\n|E| = ${Math.hypot(e.ex,e.ey).toExponential(4)} N/C`;f.textContent='E = kq r / |r|³'}else if(mode==='potential'){r.textContent=`probe = (${last.x.toFixed(2)}, ${last.y.toFixed(2)}) m\nV = ${V(last.x,last.y).toExponential(4)} V`;f.textContent='V = Σ kq/r'}else if(mode==='gauss'){const q=probe();r.textContent=`enclosed charge = ${q.toExponential(4)} C\nflux = ${(q/EPS).toExponential(4)} N·m²/C`;f.textContent='∮ E·dA = Qenc / ε₀'}else if(mode==='ampere'){const I=wires.reduce((s,w)=>s+(w.x*w.x+w.y*w.y<=+$('em-rad').value**2?w.I:0),0);r.textContent=`enclosed current = ${I.toFixed(4)} A\n∮B·dl = ${(MU*I).toExponential(4)} T·m`;f.textContent='∮ B·dl = μ₀ Ienc'}else{const q=force();r.textContent=q?`Ex = ${q.ex.toExponential(3)} N/C\nEy = ${q.ey.toExponential(3)} N/C\nBz = ${q.b.toExponential(3)} T\n|F| = ${q.f.toExponential(3)} N`:'Place a test particle first';f.textContent='F = q(E + v × B)'}}
function draw(){const s=world();ctx.clearRect(0,0,s.w,s.h);ctx.fillStyle='#08121b';ctx.fillRect(0,0,s.w,s.h);grid();if((mode==='field'||mode==='coulomb'||mode==='potential')&&$('em-lines').checked)fieldLines();if((mode==='field'||mode==='coulomb'||mode==='potential')&&$('em-vectors').checked)vectors();if(mode==='gauss'||mode==='ampere')probe();sources();particleDraw();readout();$('em-hud').textContent=`MODE: ${mode.toUpperCase()}\nCharges: ${charges.length} · Wires: ${wires.length}`}
function setMode(m){mode=m;document.querySelectorAll('.tabs button').forEach(b=>b.classList.toggle('active',b.dataset.mode===m));draw()}
$('em-reset').onclick=reset;$('em-plus').onclick=()=>{charges.push(charge(+$('em-q').value*1e-9,0,0));draw()};$('em-minus').onclick=()=>{charges.push(charge(-Math.abs(+$('em-q').value)*1e-9,0,0));draw()};$('em-wire').onclick=()=>{wires.push({x:0,y:0,I:+$('em-cur').value});draw()};
$('em-q').oninput=e=>$('em-qout').textContent=`${(+e.target.value).toFixed(2)} nC`;$('em-cur').oninput=e=>$('em-iout').textContent=`${(+e.target.value).toFixed(0)} A`;$('em-rad').oninput=e=>{$('em-rout').textContent=`${(+e.target.value).toFixed(2)} m`;draw()};
$('em-lines').onchange=draw;$('em-vectors').onchange=draw;$('em-equip').onchange=draw;document.querySelectorAll('.tabs button').forEach(b=>b.onclick=()=>setMode(b.dataset.mode));
$('em-electron').onclick=()=>{qParticle=-ECH;mParticle=ME};$('em-proton').onclick=()=>{qParticle=ECH;mParticle=MP};$('em-place').onclick=()=>{particle={x:+$('em-px').value,y:+$('em-py').value,vx:+$('em-vx').value,vy:+$('em-vy').value};path=[];draw()};$('em-clear').onclick=()=>{path=[];draw()};$('em-run').onclick=()=>{if(particle)running=true};$('em-pause').onclick=()=>{running=false};
cv.addEventListener('pointerdown',e=>{const r=cv.getBoundingClientRect(),p=P(e.clientX-r.left,e.clientY-r.top);let hit=charges.find(a=>Math.hypot(a.x-p.x,a.y-p.y)<.25);if(hit){drag=hit;cv.setPointerCapture(e.pointerId)}else{last=p;draw()}});cv.addEventListener('pointermove',e=>{const r=cv.getBoundingClientRect(),p=P(e.clientX-r.left,e.clientY-r.top);last=p;if(drag){drag.x=p.x;drag.y=p.y;draw()}});cv.addEventListener('pointerup',()=>drag=null);cv.addEventListener('wheel',e=>{e.preventDefault();zoom=Math.max(25,Math.min(140,zoom*(e.deltaY<0?1.1:.9)));draw()},{passive:false});
function tick(){if(running&&particle){const dt=.000001,l=force();if(l){particle.vx+=l.fx/mParticle*dt;particle.vy+=l.fy/mParticle*dt;particle.x+=particle.vx*dt;particle.y+=particle.vy*dt;path.push({x:particle.x,y:particle.y});if(path.length>800)path.shift()}}draw();requestAnimationFrame(tick)}
window.addEventListener('resize',size);reset();requestAnimationFrame(tick);setTimeout(size,0);
})();